### ISSUE TITLE
What is `isActive` meant for?

### ISSUE THREAD

**Issue by smessmer** [AscendingCreations/AxumSessionAuth#19]
What is `isActive` meant for?
Also, I understand what `isAnonymous` and `isAuthenticated` mean, although I'm a bit confused why we need both. Is there any scenario where the following equality is not true?
```rust
isAnonymous() == ! isAuthenticated()
```

**Comment by genusistimelord** [comment]
well there could be a case where 

isAnonymous = false and isAuthenticated = false as well. For cases where they registered but did not activate the account via email code/url.

is_active is there for if you want to make a system to log them out if they are inactive. Generally this was based on a Old python source a while back which i just adapted over to adapt my website over to rust.

**Comment by smessmer** [comment]
thanks
