### ISSUE TITLE
impl DatabasePool for Box<dyn DatabasePool>

### ISSUE THREAD

**Issue by smessmer** [AscendingCreations/AxumSessionAuth#20]
I am writing a web application that uses sqlite in developer builds and postgres in production builds. The decision between the databases is made at runtime based on an environment variable. This currently does not work with `axum-session-auth`, because the generic parameter on `AuthSession` requires a choice between postgres and sqlite. I think it would make sense to `impl DatabasePool for Box<dyn DatabasePool>`, then I could just use `Box<dyn DatabasePool>` as the generic parameter for an `AuthSession` and have it  decide at runtime which database to use.

**Comment by smessmer** [comment]
Actually, it may have to be `impl DatabasePool for Arc<dyn DatabasePool>` because `AuthSessionLayer` requires it to be `Clone` and `Box<dyn DatabasePool + Clone>` isn't supported by rust

**Comment by genusistimelord** [comment]
this would be a issue on axum_session and not axum_session_auth as that is where the actual database's are. the only thing axum_sesison_auth does is just relay the database based on the Sessions settings. So you either need to add support for what you need via a PR or you can make your Own Database type and impl database to it. and there is no need for a PR then. you can see the databases here as an example. https://github.com/AscendingCreations/AxumSession/tree/main/src/databases

There is no need to Arc the type itself if you use a wrapper that can arc the correct types inside it and redirect it to the correct database.

**Comment by smessmer** [comment]
I've implemented it in my own codebase. Here's the snippet in case others find this useful as well:

```rust
use async_trait::async_trait;
use axum_session::{databases::DatabasePool, SessionError};
use std::fmt::Debug;
use std::sync::Arc;

/// [axum_session_auth] requires a database pool as a generic parameter, and they offer choices for pg and sqlite.
/// But we want to support both pg and sqlite, so we implement one that dispatches at runtime
#[derive(Clone)]
pub struct DbPoolForSession {
    pool: Arc<dyn DatabasePool + Send + Sync>,
}

impl DbPoolForSession {
    pub fn new(pool: Arc<dyn DatabasePool + Send + Sync>) -> Self {
        Self { pool }
    }
}

impl Debug for DbPoolForSession {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DbPoolForSession").finish()
    }
}

#[async_trait]
impl DatabasePool for DbPoolForSession {
    async fn initiate(&self, table_name: &str) -> Result<(), SessionError> {
        self.pool.initiate(table_name).await
    }

    async fn count(&self, table_name: &str) -> Result<i64, SessionError> {
        self.pool.count(table_name).await
    }

    async fn store(
        &self,
        id: &str,
        session: &str,
        expires: i64,
        table_name: &str,
    ) -> Result<(), SessionError> {
        self.pool.store(id, session, expires, table_name).await
    }

    async fn load(&self, id: &str, table_name: &str) -> Result<Option<String>, SessionError> {
        self.pool.load(id, table_name).await
    }

    async fn delete_one_by_id(&self, id: &str, table_name: &str) -> Result<(), SessionError> {
        self.pool.delete_one_by_id(id, table_name).await
    }

    async fn exists(&self, id: &str, table_name: &str) -> Result<bool, SessionError> {
        self.pool.exists(id, table_name).await
    }

    async fn delete_by_expiry(&self, table_name: &str) -> Result<Vec<String>, SessionError> {
        self.pool.delete_by_expiry(table_name).await
    }

    async fn delete_all(&self, table_name: &str) -> Result<(), SessionError> {
        self.pool.delete_all(table_name).await
    }

    async fn get_ids(&self, table_name: &str) -> Result<Vec<String>, SessionError> {
        self.pool.get_ids(table_name).await
    }

    fn auto_handles_expiry(&self) -> bool {
        self.pool.auto_handles_expiry()
    }
}
```

**Comment by smessmer** [comment]
Would you prefer this newtype implementation, maybe with a better name (`DynDatabasePool`? `ArcDatabasePool`?) or would you prefer a direct `impl DatabasePool for Arc<dyn DatabasePool>`?. If for `Arc`, then also for `Box`? `Rc`? Or just for `T: Deref<DatabasePool>`? The axum-session-auth use case only needs `Arc` and for that, `Box` doesn't work because of the trait bounds on `AuthSessionLayer` which require it to be `Clone` (and `Box` isn't `Clone`). But maybe other use cases want other smart pointers?

**Comment by genusistimelord** [comment]
Call it SessionAnyPool as this will match the current naming schema and Any basically stands for anything. 
I would also like you to add an Example using this pool to the example folder too.
