### ISSUE TITLE
Surrealdb integration example

### ISSUE THREAD

**Issue by MinaMatta98** [AscendingCreations/AxumSessionAuth#24]
Hello,

Where there any surrealdb integration examples?

Specifically, this line does not compile:

```rust
        .layer(AuthSessionLayer::<User, i64, SessionPgPool, PgPool>::new(Some(poll)).with_config(auth_config));
```

When swapped out for surreal session pool and surreal client.

**Comment by genusistimelord** [comment]
what version are you currently using and with what Axum? Also what is the error message?

**Comment by genusistimelord** [comment]
I have added an Example for surreal to the example folder.

**Comment by MinaMatta98** [comment]
> what version are you currently using and with what Axum? Also what is the error message?

I was using axum 0.6.1, the problem was the tower service implementation..

I will give it a shot. Thank you.

**Comment by genusistimelord** [comment]
the latest version of axum_session does not use axum 0.6 anymore we have moved to axum 0.7 since 0.10.0 if you need to use axum 0.6 use axum_session 0.9.0

**Comment by MinaMatta98** [comment]
Hello,

This works as intended. Thank you.
