### ISSUE TITLE
'axum session extension is not loaded' after update to ver. 0.14.0

### ISSUE THREAD

**Issue by dxps** [AscendingCreations/AxumSessionAuth#30]
Hey everyone!

First of all, thank for creating and sharing this very useful library! :pray: :beers: 

I am trying to update to version 0.14.0 and I'm facing a strange issue: at first request after the server starts it logs the error:
```
2024-05-04T16:33:25.766Z ERROR [axum_session_auth::service] axum session extension is not loaded.
```

I used it without a problem with version 0.12.1, so I may miss something, but I can't figure it out.

The dependencies used (in `Cargo.toml`) are:
```toml
axum_session = { version = "0.14.0", optional = true }
axum_session_auth = { version = "0.14.0", optional = true }
axum_session_sqlx = { version = "0.1.0", features = [ "postgres", "tls-rustls" ], optional = true }
```

Based on the previous setup, and compared with [this (sqlx based)](https://github.com/AscendingCreations/AxumSessionAuth/blob/main/examples/sqlx-example/src/main.rs) example, I have this Axum setup:

```rs
        let session_config = SessionConfig::default().with_table_name("users_sessions");
        let auth_config = AuthConfig::<i64>::default().with_anonymous_user_id(Some(1));
        let session_store = SessionPgSessionStore::new(Some(pg_pool.clone().into()), session_config)
            .await
            .unwrap();

        User::create_user_tables(&pg_pool).await;

        // Build our application web api router.
        let web_api_router = Router::new()
            // Server side render the application, serve static assets, and register server functions.
            .serve_dioxus_application(ServeConfig::builder().build(), move || VirtualDom::new(app_fn))
            .await
            .layer(AuthSessionLayer::<User, i64, SessionAnyPool, PgPool>::new(Some(pg_pool)).with_config(auth_config))
            .layer(SessionLayer::new(session_store));
```

The complete app example can be found [here](https://github.com/dxps/dioxus_playground/tree/main/dioxus_axum_auth_pgdb).

Am I missing something, please?

Thanks in advance!

---

A specific postgres example for `axum_session_auth` would definitely help (as we have [this one](https://github.com/AscendingCreations/AxumSession/blob/main/examples/postgres/src/main.rs) for `axum_session`).

This also helps quickly figuring out the needed changes, as the readme of both packages (`axum_session` and `axum_session_auth`) is not yet updated to reflect the usage of `SessionPgSessionStore` instead of `SessionStore::<SessionPgPool>`.

**Comment by genusistimelord** [comment]
you can use either SessionPgSessionStore instead of SessionStore::<SessionPgPool>.I never updated to switch since it doesnt matter which one you use. its just a type shortcut. 

Also have you tried doing a Cargo clean and then Cargo update. just in case a older version got stuck. as i do run my examples to make sure they run before publishing them. I have also never used dioxus so i am unsure if they need any thing specific to run it. so just try the cargo clean and cargo update and get back with me. sometimes older versions get stuck.

**Comment by dxps** [comment]
Thanks for the quick feedback, Andrew! :pray: 

The problem was that the code was inconsistenly updated: some parts used `SessionPgPool`, while others used `SessionAnyPool`.

Therefore, the solution was to use `SessionPgPool` everywhere applicable (Axum config and extractor, plus owned/custom `Session` struct).

**Comment by genusistimelord** [comment]
ahh I am glad you figured out the issue! Also no problem I tend to help as soon as I see anyone asking.
