### ISSUE TITLE
Wrong log level when user found in cache

### ISSUE THREAD

**Issue by jhoobergs** [AscendingCreations/AxumSessionAuth#32]
At https://github.com/AscendingCreations/AxumSessionAuth/blob/main/src/service.rs#L94C1-L94C74 a `warn` logging is used to log that a user is found in the cache, but I assume that finding a user in a cache is expected behavior? It seems better to change this to a `debug` log. 

Or is there a specific reason why this is a warn log? It floods my server logs...

**Comment by genusistimelord** [comment]
Yes, it should be set as Debug. If you want, I will accept a PR fixing log levels and even adding Extra loggers.

**Comment by jhoobergs** [comment]
Thanks for merging. Would it be possible to make a new release?

**Comment by genusistimelord** [comment]
I can make a small revision release for this tomorrow.

**Comment by genusistimelord** [comment]
Released on crates.
