### ISSUE TITLE
How can I implement login using PostgreSQL (pg), then store the token in Redis for authentication, and obtain the user permissions in PostgreSQL through the token stored in Redis?

### ISSUE THREAD

**Issue by tqq1994516** [AscendingCreations/AxumSessionAuth#34]
I am trying to use these three crates`axum_session_auth`、`axum_session`、`axum_session_redispool` in the SSR mode of leptos_axum.
I don't know how to achieve the effect I want. For example, the `load_user` method in the` Authentication` trait seems to be able to operate only by using either a PostgreSQL (pg) or Redis connection.I cannot use both PostgreSQL (pg) and Redis in this method.
![image](https://github.com/user-attachments/assets/c31906f0-764a-4e84-b3f2-c809bdd3d435)

**Comment by genusistimelord** [comment]
Not sure why you would Want to use both methods. But it is possible to use both if you make a wrapper struct for it first. The wrapper just needs to support what the Pool Trait requires.  The only one that can not use both at once would be AxumSession as there is no way or means to use 2 separate ones here.

but for user loading generally this is to load them from a Database or a File. it is not really meant to be housed in a non persistent database like Redis.

**Comment by tqq1994516** [comment]
> Not sure why you would Want to use both methods. But it is possible to use both if you make a wrapper struct for it first. The wrapper just needs to support what the Pool Trait requires. The only one that can not use both at once would be AxumSession as there is no way or means to use 2 separate ones here.
> 
> but for user loading generally this is to load them from a Database or a File. it is not really meant to be housed in a non persistent database like Redis.

Okay, I understand. Since the session ID is only temporarily stored and is frequently accessed for verification, it is intended to be placed in Redis. User verification and authentication are only read from the database during login and access, so they are intended to be separated.
