### ISSUE TITLE
Why was axum_sessions_auth yanked?

### ISSUE THREAD

**Issue by bbigras** [AscendingCreations/AxumSessionAuth#35]
Why was every versions on https://crates.io/crates/axum_sessions_auth/versions yanked?

I don't seem able to find any information about that.

**Comment by genusistimelord** [comment]
It was renamed to axum session Auth and those versions were discontinued. This was due to a rewrite and rename of axum database sessions to axum session. Which was planned for quiet a while back then

Please use https://crates.io/crates/axum_session_auth
